
-- Preview first 5 rows
SELECT * FROM CD_sales_data LIMIT 5;

-- Monthly Revenue and Order Volume
-- This query calculates the total revenue and total number of unique orders for each month and year
/*
SELECT
    year,
    month,
    SUM(revenue) AS total_revenue,
    COUNT(DISTINCT order_ID) AS order_volume
FROM
    CD_sales_data
GROUP BY
    year, month
ORDER BY
    year,
    CASE
        WHEN month = 'January' THEN 1
        WHEN month = 'February' THEN 2
        WHEN month = 'March' THEN 3
        WHEN month = 'April' THEN 4
        WHEN month = 'May' THEN 5
        WHEN month = 'June' THEN 6
        WHEN month = 'July' THEN 7
        WHEN month = 'August' THEN 8
        WHEN month = 'September' THEN 9
        WHEN month = 'October' THEN 10
        WHEN month = 'November' THEN 11
        WHEN month = 'December' THEN 12
    END;
*/

-- Top 3 Months by Revenue
-- This query returns the top 3 months with the highest revenue
/*
SELECT
    year,
    month,
    SUM(revenue) AS total_revenue
FROM
    CD_sales_data
GROUP BY
    year, month
ORDER BY
    total_revenue DESC
LIMIT 3;
*/

-- Monthly Revenue by Country
-- This query shows how much revenue each country earned every month
/*
SELECT
    year,
    month,
    product_category,
    SUM(revenue) AS category_revenue
FROM
    CD_sales_data
GROUP BY
    year, month, product_category
ORDER BY
    year, month, category_revenue DESC;
*/

-- Most Popular Products by Total Orders
-- Find top 5 products based on how many units were sold
/*
SELECT
    product,
    SUM(order_quantity) AS total_quantity_ordered,
    COUNT(DISTINCT order_ID) AS total_orders
FROM
    CD_sales_data
GROUP BY
    product
ORDER BY
    total_quantity_ordered DESC
LIMIT 5;
*/

-- Monthly Profit Trend
-- This query calculates total profit earned each month
/*
SELECT
    year,
    month,
    SUM(profit) AS monthly_profit
FROM
    CD_sales_data
GROUP BY
    year, month
ORDER BY
    year,
    CASE
        WHEN month = 'January' THEN 1
        WHEN month = 'February' THEN 2
        WHEN month = 'March' THEN 3
        WHEN month = 'April' THEN 4
        WHEN month = 'May' THEN 5
        WHEN month = 'June' THEN 6
        WHEN month = 'July' THEN 7
        WHEN month = 'August' THEN 8
        WHEN month = 'September' THEN 9
        WHEN month = 'October' THEN 10
        WHEN month = 'November' THEN 11
        WHEN month = 'December' THEN 12
    END;
*/

-- Sales by Age Group
-- Check which customer age groups bring the most revenue and orders.
/*
SELECT
    age_group,
    SUM(revenue) AS total_revenue,
    SUM(order_quantity) AS total_quantity
FROM
    CD_sales_data
GROUP BY
    age_group
ORDER BY
    total_revenue DESC;  
*/

-- Monthly Sales by Product Category
-- Revenue generated by each product category every month
/*
SELECT
    year,
    month,
    product_category,
    SUM(revenue) AS category_sales
FROM
    CD_sales_data
GROUP BY
    year, month, product_category
ORDER BY
    year, month, category_sales DESC;
*/

-- Top 3 Countries by Revenue
-- Find the top 3 countries that generated the most revenue
/*
SELECT
    country,
    SUM(revenue) AS total_revenue
FROM
    CD_sales_data
GROUP BY
    country
ORDER BY
    total_revenue DESC
LIMIT 3;
*/

-- Average Unit Price per Product Category
-- What is the avg unit price in each product category
SELECT
    product_category,
    ROUND(AVG(unit_price), 2) AS avg_price
FROM
    CD_sales_data
GROUP BY
    product_category
ORDER BY
    avg_price DESC;
